# Jekyll configuration for Open SDG platform

baseurl: "/site"
remote_data_prefix: 'https://sdg-dti-odd.github.io/data'

languages:
  - fr
  - en
# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.1.0


# Replace this title as needed.
title: general.site_title
url: ""
environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

#site_config
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: IEDS
  adjective: de l'IEDS
create_goals:
  previous_next_links: false
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  # - title: Téléchargez l'examen local volontaire partiel
  #   content: ''
  #   include: components/download-elv.html
  #   button_label: ''
  #   button_link: ''
  #   rule_color: ''
  - title: Téléchargez l'examen local volontaire
    content: |
      Convertir le contenu de la plateforme en un document PDF d'analyse des progrès de la communauté.
  
      _Le contenu peut prendre entre 5 et 10 minutes pour se mettre à jour_
    button_label: "Téléchargez l'examen local volontaire (PDF)"
    button_link: https://sdg-dti-odd.github.io/data/fr/output.pdf
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: Données sur les objectifs de développement durable au Québec
  description: Bienvenue à la plateforme de données ouvertes pour la mise en œuvre locale des objectifs de développement durable au Québec.
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - analysis
    - community
    - initiatives
    - national
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: chart
  tab_2: table
  tab_3: map
  tab_4: hide
languages_public: []
logos: []
map_layers: []
map_options:
  #disaggregation_controls: true #whether to show disaggregation controls on the map
  minZoom: 5
  maxZoom: 10
  tileURL: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  tileOptions:
 # attribution: 'My map attribution'
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#deebf7'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#3182bd'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
map_layers:
  - min_zoom: 5
    max_zoom: 10
    subfolder: regions
    label: Regions
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: ''
  # - scope: global
  #   title: indicator.global_metadata
  - scope: analysis
    title: "Analyse des tendances"
    description: "Analyser ici les tendances de l'indicateur."
  - scope: community
    title: "Défis et progrès de la communauté"
    description: "Décrire ici les défis et progrès de la communauté liés à l'indicateur"
  - scope: initiatives
    title: "Initiatives de la communauté"
    description: "Inscrire ici les initiatives de la municipalités liées à cet indicateur."
    
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://sdg-dti-odd.github.io/data'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/sdg-dti-odd/data'
repository_url_site: 'https://github.com/sdg-dti-odd/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''


# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

bootstrap_5: true
chartjs_3: true
